import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import mdx from '@astrojs/mdx';
import astroExpressiveCode from 'astro-expressive-code';

export default defineConfig({
	site: 'https://a11ykr.github.io/',
	base: '/docs/',
	integrations: [
		astroExpressiveCode(),
		mdx(),
		starlight({
			title: 'A11Y KR Docs',
			logo: {
				src: '/src/assets/a11ykr.png',
				replacesTitle: true,
			},
			defaultLocale: 'root',
			locales: {
				root: {
					label: '한국어',
					lang: 'ko',
				},
			},
			social: {
				github: 'https://a11ykr.github.io',
			},
			customCss: [
				'./src/styles/custom.css'
			],
			sidebar: [
				{ label: '표준 및 지침',
					collapsed: false,
					items: [
						'guides',
						{
							label: 'WCAG 2',
							collapsed: false,
							items: [
								'guides/wcag2/wcag22-231005',
							]
						},
						{
							label: 'WCAG 2 이해(작업 중)',
							collapsed: true,
							items: [
								'guides/wcag2understanding',
								'guides/wcag2understanding/text-alternatives',
								'guides/wcag2understanding/non-text-content',
								'guides/wcag2understanding/time-based-media',
								'guides/wcag2understanding/audio-only-and-video-only-prerecorded',
								'guides/wcag2understanding/captions-prerecorded',
								'guides/wcag2understanding/audio-description-or-media-alternative-prerecorded',
								'guides/wcag2understanding/captions-live',
								'guides/wcag2understanding/audio-description-prerecorded',
								'guides/wcag2understanding/sign-language-prerecorded',
								'guides/wcag2understanding/extended-audio-description-prerecorded',
								'guides/wcag2understanding/media-alternative-prerecorded',
								'guides/wcag2understanding/audio-only-live',
								'guides/wcag2understanding/adaptable',
								'guides/wcag2understanding/info-and-relationships',
								'guides/wcag2understanding/meaningful-sequence',
								'guides/wcag2understanding/sensory-characteristics',
								'guides/wcag2understanding/orientation',
								'guides/wcag2understanding/identify-input-purpose',
								'guides/wcag2understanding/identify-purpose',
								'guides/wcag2understanding/distinguishable',
								'guides/wcag2understanding/use-of-color',
								'guides/wcag2understanding/audio-control',
								'guides/wcag2understanding/contrast-minimum',
								'guides/wcag2understanding/resize-text',
								'guides/wcag2understanding/images-of-text',
								'guides/wcag2understanding/contrast-enhanced',
								'guides/wcag2understanding/low-or-no-background-audio',
								'guides/wcag2understanding/visual-presentation',
								'guides/wcag2understanding/images-of-text-no-exception',
								'guides/wcag2understanding/reflow',
								'guides/wcag2understanding/non-text-contrast',
								'guides/wcag2understanding/text-spacing',
								'guides/wcag2understanding/content-on-hover-or-focus',
								'guides/wcag2understanding/keyboard-accessible',
								'guides/wcag2understanding/keyboard',
								'guides/wcag2understanding/no-keyboard-trap',
								'guides/wcag2understanding/keyboard-no-exception',
								'guides/wcag2understanding/character-key-shortcuts',
								'guides/wcag2understanding/enough-time',
								'guides/wcag2understanding/timing-adjustable',
								'guides/wcag2understanding/pause-stop-hide',
								'guides/wcag2understanding/no-timing',
								'guides/wcag2understanding/interruptions',
								'guides/wcag2understanding/re-authenticating',
								'guides/wcag2understanding/timeouts',
								'guides/wcag2understanding/seizures-and-physical-reactions',
								'guides/wcag2understanding/three-flashes-or-below-threshold',
								'guides/wcag2understanding/three-flashes',
								'guides/wcag2understanding/animation-from-interactions',
								'guides/wcag2understanding/navigable',
								'guides/wcag2understanding/bypass-blocks',
								'guides/wcag2understanding/page-titled',
								'guides/wcag2understanding/focus-order',
								'guides/wcag2understanding/link-purpose-in-context',
								'guides/wcag2understanding/multiple-ways',
								'guides/wcag2understanding/headings-and-labels',
								'guides/wcag2understanding/focus-visible',
								'guides/wcag2understanding/location',
								'guides/wcag2understanding/link-purpose-link-only',
								'guides/wcag2understanding/section-headings',
								'guides/wcag2understanding/focus-not-obscured-minimum',
								'guides/wcag2understanding/focus-not-obscured-enhanced',
								'guides/wcag2understanding/focus-appearance',
								'guides/wcag2understanding/input-modalities',
								'guides/wcag2understanding/pointer-gestures',
								'guides/wcag2understanding/pointer-cancellation',
								'guides/wcag2understanding/label-in-name',
								'guides/wcag2understanding/motion-actuation',
								'guides/wcag2understanding/target-size-enhanced',
								'guides/wcag2understanding/concurrent-input-mechanisms',
								'guides/wcag2understanding/dragging-movements',
								'guides/wcag2understanding/target-size-minimum',
								'guides/wcag2understanding/readable',
								'guides/wcag2understanding/language-of-page',
								'guides/wcag2understanding/language-of-parts',
								'guides/wcag2understanding/unusual-words',
								'guides/wcag2understanding/abbreviations',
								'guides/wcag2understanding/reading-level',
								'guides/wcag2understanding/pronunciation',
								'guides/wcag2understanding/predictable',
								'guides/wcag2understanding/on-focus',
								'guides/wcag2understanding/on-input',
								'guides/wcag2understanding/consistent-navigation',
								'guides/wcag2understanding/consistent-identification',
								'guides/wcag2understanding/change-on-request',
								'guides/wcag2understanding/consistent-help',
								'guides/wcag2understanding/input-assistance',
								'guides/wcag2understanding/error-identification',
								'guides/wcag2understanding/labels-or-instructions',
								'guides/wcag2understanding/error-suggestion',
								'guides/wcag2understanding/error-prevention-legal-financial-data',
								'guides/wcag2understanding/help',
								'guides/wcag2understanding/error-prevention-all',
								'guides/wcag2understanding/redundant-entry',
								'guides/wcag2understanding/accessible-authentication-minimum',
								'guides/wcag2understanding/accessible-authentication-enhanced',
								'guides/wcag2understanding/compatible',
								'guides/wcag2understanding/parsing',
								'guides/wcag2understanding/name-role-value',
								'guides/wcag2understanding/status-messages',
								'guides/wcag2understanding/intro',
								'guides/wcag2understanding/understanding-techniques',
								'guides/wcag2understanding/understanding-act-rules',
								'guides/wcag2understanding/conformance',
								'guides/wcag2understanding/refer-to-wcag',
								'guides/wcag2understanding/documenting-accessibility-support',
								'guides/wcag2understanding/understanding-metadata',
							]
						},
					]
				},
				{
					label: '참고 자료',
					collapsed: false,
					autogenerate: {
						directory: '/reference/',
						order: 'asc',
						pathPrefix: '/reference'
					}
				},
				{ label: '접근성 점검 도구', link: '/acts/' },
				{
					label: '용어집',
					collapsed: true,
					autogenerate: {
						directory: '/glossary/',
						order: 'asc',
						pathPrefix: '/glossary'
					}
				},
			],
		}),
	],
});