import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import mdx from '@astrojs/mdx';
import astroExpressiveCode from 'astro-expressive-code';

export default defineConfig({
	site: 'https://a11ykr.github.io/',
	base: '/docs/',
	integrations: [
		astroExpressiveCode(),
		mdx(),
		starlight({
			title: 'A11Y KR Docs',
			logo: {
				src: '/src/assets/a11ykr.png',
				replacesTitle: true,
			},
			defaultLocale: 'root',
			locales: {
				root: {
					label: '한국어',
					lang: 'ko',
				},
			},
			social: {
				github: 'https://a11ykr.github.io',
			},
			customCss: [
				'./src/styles/custom.css'
			],
			sidebar: [
				{ label: '표준 및 지침',
					collapsed: false,
					items: [
						'guides',
						{
							label: 'WCAG 2',
							collapsed: false,
							items: [
								'guides/wcag2/wcag22-231005',
								{
									label: 'WCAG 2 이해(작업 중)',
									collapsed: true,
									items: [
										'guides/wcag2/understanding',
										'guides/wcag2/understanding/text-alternatives',
										'guides/wcag2/understanding/non-text-content',
										'guides/wcag2/understanding/time-based-media',
										'guides/wcag2/understanding/audio-only-and-video-only-prerecorded',
										'guides/wcag2/understanding/captions-prerecorded',
										'guides/wcag2/understanding/audio-description-or-media-alternative-prerecorded',
										'guides/wcag2/understanding/captions-live',
										'guides/wcag2/understanding/audio-description-prerecorded',
										'guides/wcag2/understanding/sign-language-prerecorded',
										'guides/wcag2/understanding/extended-audio-description-prerecorded',
										'guides/wcag2/understanding/media-alternative-prerecorded',
										'guides/wcag2/understanding/audio-only-live',
										'guides/wcag2/understanding/adaptable',
										'guides/wcag2/understanding/info-and-relationships',
										'guides/wcag2/understanding/meaningful-sequence',
										'guides/wcag2/understanding/sensory-characteristics',
										'guides/wcag2/understanding/orientation',
										'guides/wcag2/understanding/identify-input-purpose',
										'guides/wcag2/understanding/identify-purpose',
										'guides/wcag2/understanding/distinguishable',
										'guides/wcag2/understanding/use-of-color',
										'guides/wcag2/understanding/audio-control',
										'guides/wcag2/understanding/contrast-minimum',
										'guides/wcag2/understanding/resize-text',
										'guides/wcag2/understanding/images-of-text',
										'guides/wcag2/understanding/contrast-enhanced',
										'guides/wcag2/understanding/low-or-no-background-audio',
										'guides/wcag2/understanding/visual-presentation',
										'guides/wcag2/understanding/images-of-text-no-exception',
										'guides/wcag2/understanding/reflow',
										'guides/wcag2/understanding/non-text-contrast',
										'guides/wcag2/understanding/text-spacing',
										'guides/wcag2/understanding/content-on-hover-or-focus',
										'guides/wcag2/understanding/keyboard-accessible',
										'guides/wcag2/understanding/keyboard',
										'guides/wcag2/understanding/no-keyboard-trap',
										'guides/wcag2/understanding/keyboard-no-exception',
										'guides/wcag2/understanding/character-key-shortcuts',
										'guides/wcag2/understanding/enough-time',
										'guides/wcag2/understanding/timing-adjustable',
										'guides/wcag2/understanding/pause-stop-hide',
										'guides/wcag2/understanding/no-timing',
										'guides/wcag2/understanding/interruptions',
										'guides/wcag2/understanding/re-authenticating',
										'guides/wcag2/understanding/timeouts',
										'guides/wcag2/understanding/seizures-and-physical-reactions',
										'guides/wcag2/understanding/three-flashes-or-below-threshold',
										'guides/wcag2/understanding/three-flashes',
										'guides/wcag2/understanding/animation-from-interactions',
										'guides/wcag2/understanding/navigable',
										'guides/wcag2/understanding/bypass-blocks',
										'guides/wcag2/understanding/page-titled',
										'guides/wcag2/understanding/focus-order',
										'guides/wcag2/understanding/link-purpose-in-context',
										'guides/wcag2/understanding/multiple-ways',
										'guides/wcag2/understanding/headings-and-labels',
										'guides/wcag2/understanding/focus-visible',
										'guides/wcag2/understanding/location',
										'guides/wcag2/understanding/link-purpose-link-only',
										'guides/wcag2/understanding/section-headings',
										'guides/wcag2/understanding/focus-not-obscured-minimum',
										'guides/wcag2/understanding/focus-not-obscured-enhanced',
										'guides/wcag2/understanding/focus-appearance',
										'guides/wcag2/understanding/input-modalities',
										'guides/wcag2/understanding/pointer-gestures',
										'guides/wcag2/understanding/pointer-cancellation',
										'guides/wcag2/understanding/label-in-name',
										'guides/wcag2/understanding/motion-actuation',
										'guides/wcag2/understanding/target-size-enhanced',
										'guides/wcag2/understanding/concurrent-input-mechanisms',
										'guides/wcag2/understanding/dragging-movements',
										'guides/wcag2/understanding/target-size-minimum',
										'guides/wcag2/understanding/readable',
										'guides/wcag2/understanding/language-of-page',
										'guides/wcag2/understanding/language-of-parts',
										'guides/wcag2/understanding/unusual-words',
										'guides/wcag2/understanding/abbreviations',
										'guides/wcag2/understanding/reading-level',
										'guides/wcag2/understanding/pronunciation',
										'guides/wcag2/understanding/predictable',
										'guides/wcag2/understanding/on-focus',
										'guides/wcag2/understanding/on-input',
										'guides/wcag2/understanding/consistent-navigation',
										'guides/wcag2/understanding/consistent-identification',
										'guides/wcag2/understanding/change-on-request',
										'guides/wcag2/understanding/consistent-help',
										'guides/wcag2/understanding/input-assistance',
										'guides/wcag2/understanding/error-identification',
										'guides/wcag2/understanding/labels-or-instructions',
										'guides/wcag2/understanding/error-suggestion',
										'guides/wcag2/understanding/error-prevention-legal-financial-data',
										'guides/wcag2/understanding/help',
										'guides/wcag2/understanding/error-prevention-all',
										'guides/wcag2/understanding/redundant-entry',
										'guides/wcag2/understanding/accessible-authentication-minimum',
										'guides/wcag2/understanding/accessible-authentication-enhanced',
										'guides/wcag2/understanding/compatible',
										'guides/wcag2/understanding/parsing',
										'guides/wcag2/understanding/name-role-value',
										'guides/wcag2/understanding/status-messages',
										'guides/wcag2/understanding/intro',
										'guides/wcag2/understanding/understanding-techniques',
										'guides/wcag2/understanding/understanding-act-rules',
										'guides/wcag2/understanding/conformance',
										'guides/wcag2/understanding/refer-to-wcag',
										'guides/wcag2/understanding/documenting-accessibility-support',
										'guides/wcag2/understanding/understanding-metadata',
									]
								},
							]
						},
					]
				},
				{
					label: '참고 자료',
					collapsed: false,
					autogenerate: {
						directory: '/reference/',
						order: 'asc',
						pathPrefix: '/reference'
					}
				},
				{ label: '접근성 점검 도구', link: '/acts/' },
				{
					label: '용어집',
					collapsed: true,
					autogenerate: {
						directory: '/glossary/',
						order: 'asc',
						pathPrefix: '/glossary'
					}
				},
			],
		}),
	],
});